version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'db_mysql'
      MYSQL_USER: 'user_mysql'
      MYSQL_PASSWORD: 'localhost'
    ports:
      - '3306:3306'
    volumes:
      - ./db1_lib_ucdavis_edu.sql:/docker-entrypoint-initdb.d/db1_lib_ucdavis_edu.sql

  migrate:
    build: .
    environment:
      PGUSER: postgres
      PGHOST: host.docker.internal
      PGDATABASE: postgres
      PGPASSWORD: localhost
      PGPORT: 5432
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: localhost
      MYSQL_ROOT_PASSWORD: 'root_password'
      UCDLIB_PERSONNEL_API_USER: ${UCDLIB_PERSONNEL_API_USER}
      UCDLIB_PERSONNEL_API_KEY: ${UCDLIB_PERSONNEL_API_KEY}
    volumes:
      - ./src:/migration/src
      - ./index.js:/migration/index.js
    # ports: 
    #   - 5432:5432
    depends_on:
      - mysql
    # command: ./wait-for-it.sh
    command: /app/lib/tail.sh
    #command: node run.js # Replace with your migration command

