x-variables:
  main-image: &main-image localhost/local-dev/ucdlib-travel:local-dev
services:
  app:
    image: *main-image
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}
    depends_on:
      - db
    environment:
      APP_ROOT_URL: ${APP_ROOT_URL:-http://localhost:3000}
      APP_ENV: ${APP_ENV:-dev}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      APP_SMTP_SYSTEM_EMAIL_ADDRESS: ${APP_SMTP_SYSTEM_EMAIL_ADDRESS:-librarywst@ucdavis.edu}
      APP_REPORT_ERRORS_URL: ${APP_REPORT_ERRORS_URL:-https://client-error-reporter-akwemh35fa-uw.a.run.app}
      BACKUP_LOG_TABLE: ${BACKUP_LOG_TABLE:-backup_log}
    volumes:
      - ../../../src:/app
      - /app/node_modules
      - uploads-data:/uploads
    # command: ./start-server.sh
    command: ./lib/tail.sh
  init:
    image: *main-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      RUN_INIT: true
      INIT_DATA_ENV: ${INIT_DATA_ENV:-prod}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: itis-backups/travel
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../../../utils/init:/app/deploy-utils/init
      - ../../secrets/gc-reader-key.json:/etc/service-account.json
      - uploads-data:/uploads
    # command: /app/lib/tail.sh
    command: ./deploy-utils/init/init.sh
  backup:
    image: *main-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      # RUN_BACKUP: true
      BACKUP_DATA_ENV: ${BACKUP_DATA_ENV:-localhost}
      BACKUP_LOG_TABLE: ${BACKUP_LOG_TABLE:-backup_log}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: itis-backups/travel
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../../../utils/backup:/app/deploy-utils/backup
      - ../../secrets/gc-writer-key.json:/etc/service-account.json
      - uploads-data:/uploads
    # command: ./deploy-utils/backup/entrypoint.sh
    command: /app/lib/tail.sh
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: localhost
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ../../db-entrypoint:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080
volumes:
  db-data:
  uploads-data:
