version: '3'
services:
  app:
    image: gcr.io/digital-ucdavis-edu/simple-spa:main
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: ./start-server.sh
  init:
    image: gcr.io/digital-ucdavis-edu/simple-spa:main
    env_file:
      - .env
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: 
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../../gc-reader-key.json:/etc/service-account.json
    command: ./deploy-utils/init/init.sh
  backup:
    image: gcr.io/digital-ucdavis-edu/simple-spa:main
    env_file:
      - .env
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: 
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../../gc-writer-key.json:/etc/service-account.json
    command: ./deploy-utils/backup/entrypoint.sh
  db:
    image: postgres:15.3
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
