version: '3'
services:
  app:
    image: gcr.io/ucdlib-pubreg/ucdlib-travel:dev
    env_file:
      - .env
    environment:
      APP_ROOT_URL: ${APP_ROOT_URL:-https://travel.staff.library.ucdavis.edu}
    ports:
      - ${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}
    depends_on:
      - db
    restart: always
    volumes:
      - uploads-data:/uploads
    command: ./start-server.sh
  init:
    image: gcr.io/ucdlib-pubreg/ucdlib-travel:dev
    env_file:
      - .env
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: itis-backups/travel
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../gc-reader-key.json:/etc/service-account.json
      - uploads-data:/uploads
    command: ./deploy-utils/init/init.sh
  backup:
    image: gcr.io/ucdlib-pubreg/ucdlib-travel:dev
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: itis-backups/travel
      BACKUP_FILE_NAME: db.sql.gz
    volumes:
      - ../gc-writer-key.json:/etc/service-account.json
      - uploads-data:/uploads
    command: ./deploy-utils/backup/entrypoint.sh
  db:
    image: postgres:16
    env_file:
      - .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./db-entrypoint:/docker-entrypoint-initdb.d
volumes:
  db-data:
  uploads-data:
