import { html, css } from 'lit';

import '@ucd-lib/theme-elements/brand/ucd-theme-brand-textbox/ucd-theme-brand-textbox.js'


export function styles() {
  const elementStyles = css`
    :host {
      display: block;
    }
  `;

  return [elementStyles];
}

export function render() { 
return html`
  <div class="l-container">
    <h2 class='heading--underline'>Approvers</h2>

    <div class="approvertype_description">
      <p>When a request is submitted to this application, approval is required from a list 
        of employees determined by the funding source. Employees must be registered as an 
        approver before they can be added to the approval chain of a funding source. Some 
        approver types are automatically generated by this system and cannot be removed 
        in this section.
      </p>
    </div>

    <section class="approvertype-info">
    ${this.existingApprovers.map((approver) => html`
      <div class="approvertype-block">
          <span>
            <h3 class="section-header"><em>${approver.label}</em>
              <span class="user-icon"><i class="fa-solid fa-pen-to-square"></i></span>
              ${!approver.systemGenerated ? html`<span class="trash-icon"><i class="fa-solid fa-trash"></i></span>`:html``}
            </h3>
          </span> 
          <span>${approver.description}</span><br/>

          ${approver.employees.map((employee) => html`
            <span>
              <b style="color:#022851"><i class="fa-solid fa-user" style="color:#13639E;width:15px;height:15px;"></i>&nbsp;${!approver.systemGenerated ? html`${employee.firstName} ${employee.lastName}`:html`System Generated`}</b><br />
            </span>  
          `)}
      </div>
    `)}
    </section> 

    <section class="approvertype-form">
      <div class="l-2col layout-columns">
        <h3 class="section-header"><em>Edit Approver</em>
          <div class="field-container">
              <label class="textLabel" for="text">Label <abbr title="Required">*</abbr></label>
              <input class="inputLabel" @input=${(e) => this._setLabel(e.target.value)} type="text" placeholder="Position Title">
          </div>

          <div class="field-container">
            <label class="textDescriptionLabel" for="textarea">Description</label>
            <textarea class="textDescription" @input=${(e) => this._setDescription(e.target.value)} rows="8" cols="48" placeholder="Approver Type Description"></textarea>
        </div>

        <ucdlib-employee-search-basic></ucdlib-employee-search-basic>
      </div>

      <!-- <span>
        <p>
          <button class="btn btn--alt3">Save Button</button>
          <button class="btn btn--alt3">Cancel Button</button>
        </p>
      </span> -->
    </section>
        
    <p><button @click=${e => this._onSubmit()} class="btn btn--primary" style="margin:20px 0px 0px 0px">Add New Approver</button></p>

      
  </div>


`;}